### ISSUE TITLE
Snapshot on PVT_VM

### ISSUE THREAD

**Issue by dzhou121** [virtuozzo/pcs-nova-driver#4]
Hi,

I'm trying to using this driver for Openstack. I have a question about the snapshot on a PVT_VM. I can see you're using clone_ex to clone the machine to a template. So it means you have to power off the VM to do that? 

Thanks,

Dongdong

**Comment by dmitry-guryanov** [comment]
Hi,

Yes, you're right, you have to poweroff the VM.
